### ISSUE TITLE
Farbauswahl für die Steine

### ISSUE THREAD

**Issue by phisinger** [0xfr34ky/webeng-viergewinnt#19]
Satz an Farb-Kombinationen erzeugen.
Vor dem Spiel Spieler fragen, welche Farbkombination gewünscht wird.

**Comment by 0xfr34ky** [comment]
Wenn beim matches.colorset 0 ist, so soll einer der Teilnehmer aus 5-10 Farbkombinationen auswählen können. Diese Auswahl dann dem Server mit ajax_viergewinnt.php?set_colorset=x mitteilen. Wenn 'true' zurückgegeben wird, zum Spielfeld weiterleiten.
